package pl.marpiec.socnet.web.page.books.component

/**
 * @author Marcin Pieciukiewicz
 */

object BooksLinks {

  val ALL_BOOKS = 1
  val YOUR_BOOKS = 2
  val ADD_BOOK = 3
  val ADD_BOOK_SUGGESTION = 4
  val ALL_SUGGESTIONS = 5
  val YOUR_SUGGESTIONS = 6

  val ALL_BOOKS_LINKS = YOUR_BOOKS :: ADD_BOOK :: ADD_BOOK_SUGGESTION :: ALL_SUGGESTIONS :: YOUR_SUGGESTIONS :: Nil
  val YOUR_BOOKS_LINKS = ALL_BOOKS :: Nil
  val ADD_BOOK_LINKS = YOUR_BOOKS :: ALL_BOOKS :: Nil
  val ADD_BOOK_SUGGESTION_LINKS = YOUR_BOOKS :: ALL_BOOKS :: YOUR_SUGGESTIONS :: Nil
  val ALL_SUGGESTIONS_LINKS = ALL_BOOKS :: Nil
  val YOUR_SUGGESTIONS_LINKS = YOUR_BOOKS :: ALL_BOOKS :: ADD_BOOK_SUGGESTION :: Nil

  val BOOK_PREVIEW_LINKS = YOUR_BOOKS :: ALL_BOOKS :: Nil
  val BOOK_SUGGESTION_PREVIEW_LINKS = YOUR_BOOKS :: ALL_BOOKS :: YOUR_SUGGESTIONS :: Nil

}
